cd test fixed

diff --git a/.github/workflows/test-deployment.yaml b/.github/workflows/test-deployment.yaml
--- a/.github/workflows/test-deployment.yaml
+++ b/.github/workflows/test-deployment.yaml
@@ -23,7 +23,8 @@ jobs:
 
     - name: Configure yc CLI
       run: |
-        echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json
+        echo '${{ secrets.YC_SERVICE_ACCOUNT_KEY }}' > key.json
+        jq . key.json || (echo "Invalid JSON in service account key"; exit 1)
         yc config set service-account-key key.json
         yc config set folder-id $FOLDER_ID
 
